version: "3.8"

services:
  nginx-tp:
    container_name: nginx-tp
    build:
      context: ./nginx
      target: prod
    ports:
      - "8443:8443"
    volumes:
      - timskiproekt:/timskiproekt/static
      - /certs:/certs
#    restart: always

  timskiproekt:
    build: timskiproekt
    command: gunicorn timskiproekt.wsgi:application --bind 0.0.0.0:8080
    expose:
      - 8080
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 tp.sekuloski.mk tp.sekuloski.mk
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_SERVICES}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY_SERVICES}
    depends_on:
      - nginx-tp
      - timskiproekt-db
    volumes:
      - timskiproekt:/timskiproekt/static
#    restart: always

  timskiproekt-db: # Database for the Finances API
    image: arm64v8/postgres:16rc1-alpine3.18
    volumes:
      - postgres_data_timskiproekt:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sekuloski
      - POSTGRES_PASSWORD=sekuloski
      - POSTGRES_DB=timskiproekt_dev
#    restart: always

volumes:
  timskiproekt:
  postgres_data_timskiproekt:
